// <auto-generated />
using System;
using JourneyMentorFlights.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JourneyMentorFlights.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231104223451_initia3")]
    partial class initia3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JourneyMentorFlights.Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AirportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityIataCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryIso2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeonameId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("JourneyMentorFlights.Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlightDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("JourneyMentorFlights.Domain.Entities.Flight", b =>
                {
                    b.OwnsOne("JourneyMentorFlights.Domain.ValueObjects.Airline", "Airline", b1 =>
                        {
                            b1.Property<int>("FlightId")
                                .HasColumnType("int");

                            b1.Property<string>("Iata")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Icao")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("JourneyMentorFlights.Domain.ValueObjects.ArrivalInfo", "Arrival", b1 =>
                        {
                            b1.Property<int>("FlightId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Actual")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("ActualRunway")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Airport")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Baggage")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Delay")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Estimated")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("EstimatedRunway")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Gate")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("IATA")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ICAO")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Scheduled")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Terminal")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Timezone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("JourneyMentorFlights.Domain.ValueObjects.DepartureInfo", "Departure", b1 =>
                        {
                            b1.Property<int>("FlightId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Actual")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("ActualRunway")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Airport")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Delay")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Estimated")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime?>("EstimatedRunway")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Gate")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("IATA")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ICAO")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Scheduled")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Terminal")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Timezone")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.OwnsOne("JourneyMentorFlights.Domain.ValueObjects.FlightDetails", "FlightDetails", b1 =>
                        {
                            b1.Property<int>("FlightId")
                                .HasColumnType("int");

                            b1.Property<string>("Iata")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Icao")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Number")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");

                            b1.OwnsOne("JourneyMentorFlights.Domain.ValueObjects.Codeshared", "Codeshared", b2 =>
                                {
                                    b2.Property<int>("FlightDetailsFlightId")
                                        .HasColumnType("int");

                                    b2.Property<string>("AirlineIata")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("AirlineIcao")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("AirlineName")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FlightIata")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FlightIcao")
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("FlightNumber")
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("FlightDetailsFlightId");

                                    b2.ToTable("Flights");

                                    b2.WithOwner()
                                        .HasForeignKey("FlightDetailsFlightId");
                                });

                            b1.Navigation("Codeshared")
                                .IsRequired();
                        });

                    b.OwnsOne("JourneyMentorFlights.Domain.ValueObjects.FlightLiveDetails", "LiveDetails", b1 =>
                        {
                            b1.Property<int>("FlightId")
                                .HasColumnType("int");

                            b1.Property<decimal?>("Altitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("Direction")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<bool?>("IsGround")
                                .HasColumnType("bit");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("SpeedHorizontal")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<decimal?>("SpeedVertical")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<DateTime?>("Updated")
                                .HasColumnType("datetime2");

                            b1.HasKey("FlightId");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("FlightId");
                        });

                    b.Navigation("Airline")
                        .IsRequired();

                    b.Navigation("Arrival")
                        .IsRequired();

                    b.Navigation("Departure")
                        .IsRequired();

                    b.Navigation("FlightDetails")
                        .IsRequired();

                    b.Navigation("LiveDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
